### ISSUE TITLE
Does node-usb support bi-directional endpoints?

### ISSUE THREAD

**Issue by adjavaherian** [nonolith/node-usb#111]
I'm trying to write a bulk transfer for the [crazy radio dongle](https://wiki.bitcraze.io/doc:crazyradio:usb:index) and they say that their endpoint 1 supports in and out, which seems to be valid in chrome.usb's bulkTransfer mechanism.  Does node-usb take this directional argument?  Perhaps in the data packet?  I know you say that isosynchronous is not supported, but this is different, right?  It looks like chrome.usb supports endpoint direction in its bulkTransfer and isosync is totally different.

In the following tests, you should be able to see that the endpoint is labeled with out, but the first test succeeds in reading.  The second test fails because the endpoint "in" needs to be read so the buffer can be cleared, however, I'm not sure how to do that in this scenario.  Any ideas, or is this even supported?

Thanks!

```javascript
describe.only('Packet tests', function() {

        var iface = null;

        beforeEach(function() {
            radio = new Crazyradio();
            radio.debugLevel(4);
            device = radio.find();
        });

        afterEach(function(done){
            iface.release(true, function(err){
                console.log('releasing', err);
                radio.close(device, function(err, data){
                    console.log('after', err);
                    done();
                });
            });
        });

        it('should read a packet', function(done){
            radio.open(device, function(){

                iface = device.interface(0);
                iface.claim();

                var radioIn = iface.endpoints[1];

                console.log('radioIn', radioIn.direction, radioIn.transferType, radioIn.descriptor);

                radioIn.transfer(64, function(err, data){
                    console.log('in err / data', err, data);
                    done();
                });
            });
        });

        it('should send a packet', function(){

            radio.open(device, function(){

                iface = device.interface(0);
                iface.claim();

                var radioOut = iface.endpoints[1];

                console.log('radioOut', radioOut.direction, radioOut.transferType, radioOut.descriptor);

                //Preparing commander packet
                var packet = new ArrayBuffer(15);
                var dv = new DataView(packet);

                dv.setUint8(0, 0x30, true);      // CRTP header
                dv.setFloat32(1, 0.0, true);    // Roll
                dv.setFloat32(5, 0.0, true);   // Pitch
                dv.setFloat32(9, 0.0, true);     // Yaw
                dv.setUint16(13, 0.0, true);  // Thrust

                radioOut.transfer(packet, function(error){
                    console.log('out transfer callback', error);
                    done();
                });
            });
        });
    });
```

and here's the debug logs

```

> crazyradio-node-driver@0.0.1 test /Users/4m1r/Desktop/Crazyflie/crazyradio-node-driver
> mocha test.js



  CrazyRadio tests
    Packet tests
[timestamp] [threadID] facility level [function call] <message>
--------------------------------------------------------------------------------
[ 0.092762] [00000513] libusb: debug [libusb_get_device_list] 
[ 0.092881] [00000513] libusb: debug [libusb_get_device_descriptor] 
[ 0.092952] [00000513] libusb: debug [libusb_get_device_descriptor] 
[ 0.092993] [00000513] libusb: debug [libusb_get_device_descriptor] 
[ 0.094703] [00000513] libusb: debug [libusb_open] open 20.7
[ 0.094889] [00000513] libusb: debug [usbi_add_pollfd] add fd 22 events 1
[ 0.094903] [00000513] libusb: debug [darwin_open] device open for access
[ 0.094952] [00003f03] libusb: debug [handle_events] poll() returned 1
[ 0.094990] [00003f03] libusb: debug [handle_events] caught a fish on the control pipe
[ 0.095009] [00003f03] libusb: debug [libusb_get_next_timeout] no URBs, no timeout!
[ 0.095015] [00003f03] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.095020] [00003f03] libusb: debug [handle_events] poll fds modified, reallocating
[ 0.095026] [00003f03] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
opening
[ 0.095904] [00000513] libusb: debug [libusb_claim_interface] interface 0
[ 0.096790] [00000513] libusb: debug [get_endpoints] building table of endpoints.
[ 0.096814] [00000513] libusb: debug [get_endpoints] interface: 0 pipe 1: dir: 1 number: 1
[ 0.096821] [00000513] libusb: debug [get_endpoints] interface: 0 pipe 2: dir: 0 number: 1
[ 0.096864] [00000513] libusb: debug [darwin_claim_interface] interface opened
radioIn out 2 { bLength: 7,
  bDescriptorType: 5,
  bEndpointAddress: 1,
  bmAttributes: 2,
  wMaxPacketSize: 64,
  bInterval: 6,
  bRefresh: 0,
  bSynchAddress: 0,
  extra: <Buffer > }
[ 0.099095] [00000513] libusb: debug [ep_to_pipeRef] converting ep address 0x01 to pipeRef and interface
[ 0.099108] [00000513] libusb: debug [ep_to_pipeRef] pipe 2 on interface 0 matches
[ 0.099325] [0000230f] libusb: debug [darwin_async_io_callback] an async io operation has completed
[ 0.099359] [00003f03] libusb: debug [handle_events] poll() returned 1
[ 0.099366] [00003f03] libusb: debug [op_handle_events] checking fd 22 with revents = 1
[ 0.099370] [00003f03] libusb: debug [darwin_handle_callback] handling bulk completion with kernel status 0
[ 0.099375] [00003f03] libusb: debug [usbi_handle_transfer_completion] transfer 0x10120d808 has callback 0x102b8b935
[ 0.099389] [00003f03] libusb: debug [libusb_get_next_timeout] no URBs, no timeout!
[ 0.099393] [00003f03] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.099397] [00003f03] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
in err / data undefined undefined
      ✓ should read a packet 
[ 0.101937] [00004603] libusb: debug [libusb_release_interface] interface 0
releasing undefined
[ 0.102882] [00000513] libusb: debug [libusb_close] 
[ 0.102910] [00003f03] libusb: debug [handle_events] poll() returned 1
[ 0.102921] [00003f03] libusb: debug [handle_events] caught a fish on the control pipe
[ 0.102931] [00003f03] libusb: debug [libusb_get_next_timeout] no URBs, no timeout!
[ 0.102937] [00003f03] libusb: debug [libusb_try_lock_events] someone else is modifying poll fds
[ 0.102942] [00003f03] libusb: debug [libusb_event_handler_active] someone else is modifying poll fds
[ 0.102947] [00003f03] libusb: debug [libusb_handle_events_timeout_completed] another thread is doing event handling
[ 0.102998] [00000513] libusb: debug [usbi_remove_pollfd] remove fd 22
[ 0.103053] [00003f03] libusb: debug [libusb_get_next_timeout] no URBs, no timeout!
[ 0.103065] [00003f03] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.103070] [00003f03] libusb: debug [handle_events] poll fds modified, reallocating
[ 0.103076] [00003f03] libusb: debug [handle_events] poll() 2 fds with timeout in 60000ms
after false
[ 0.103715] [00000513] libusb: debug [libusb_get_device_list] 
[ 0.104119] [00000513] libusb: debug [libusb_open] open 20.7
[ 0.104220] [00000513] libusb: debug [usbi_add_pollfd] add fd 22 events 1
[ 0.104232] [00000513] libusb: debug [darwin_open] device open for access
[ 0.104257] [00003f03] libusb: debug [handle_events] poll() returned 1
[ 0.104272] [00003f03] libusb: debug [handle_events] caught a fish on the control pipe
[ 0.104283] [00003f03] libusb: debug [libusb_get_next_timeout] no URBs, no timeout!
[ 0.104289] [00003f03] libusb: debug [libusb_try_lock_events] someone else is modifying poll fds
[ 0.104294] [00003f03] libusb: debug [libusb_handle_events_timeout_completed] event handler was active but went away, retrying
[ 0.104299] [00003f03] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.104304] [00003f03] libusb: debug [handle_events] poll fds modified, reallocating
[ 0.104311] [00003f03] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
opening
[ 0.104699] [00000513] libusb: debug [libusb_claim_interface] interface 0
[ 0.105099] [00000513] libusb: debug [get_endpoints] building table of endpoints.
[ 0.105114] [00000513] libusb: debug [get_endpoints] interface: 0 pipe 1: dir: 1 number: 1
[ 0.105124] [00000513] libusb: debug [get_endpoints] interface: 0 pipe 2: dir: 0 number: 1
[ 0.105168] [00000513] libusb: debug [darwin_claim_interface] interface opened
radioOut out 2 { bLength: 7,
  bDescriptorType: 5,
  bEndpointAddress: 1,
  bmAttributes: 2,
  wMaxPacketSize: 64,
  bInterval: 6,
  bRefresh: 0,
  bSynchAddress: 0,
  extra: <Buffer > }
[ 0.106232] [00000513] libusb: debug [ep_to_pipeRef] converting ep address 0x01 to pipeRef and interface
[ 0.106248] [00000513] libusb: debug [ep_to_pipeRef] pipe 2 on interface 0 matches
      ✓ should send a packet 
[ 0.107096] [00004503] libusb: debug [libusb_release_interface] interface 0
releasing undefined
      1) "after each" hook

  2 passing (22ms)
  1 failing

  1) CrazyRadio tests Packet tests "after each" hook:
     Uncaught Error: Can't close device with a pending request
      at Error (native)
      at Device.usb.Device.close (/Users/4m1r/Desktop/Crazyflie/crazyradio-node-driver/node_modules/usb/usb.js:43:7)
      at Crazyradio.close (/Users/4m1r/Desktop/Crazyflie/crazyradio-node-driver/index.js:61:12)
      at Interface.<anonymous> (/Users/4m1r/Desktop/Crazyflie/crazyradio-node-driver/test.js:463:23)
      at Device.<anonymous> (/Users/4m1r/Desktop/Crazyflie/crazyradio-node-driver/node_modules/usb/usb.js:200:7)



npm ERR! Test failed.  See above for more details.
[4m1r@Korgi:14:12:28 ~/Desktop/Crazyflie/crazyradio-node-driver]
$ 

```

Here's the driver and the rest of the tests, which work fine for configuration
https://github.com/adjavaherian/crazyradio-node-driver

**Comment by kevinmehall** [comment]
USB endpoints aren't bidirectional, but the MSB of the endpoint address specifies the direction, and sometimes that bit is omitted when the direction is also specified. So there are actually two endpoints, `0x1` OUT and `0x81` IN, which `node-usb` will see as two separate endpoints.

**Comment by adjavaherian** [comment]
Thanks @kevinmehall, that's what I'm seeing, but for some reason, my read from `0x81` never returns the callback.  Any ideas?

Here's the spec

```javascript
before(function() {
            radio = new Crazyradio();
            radio.debugLevel(4);
            device = radio.find();
        });

        afterEach(function(done){
            var iface = device.interfaces[0];
            iface.release(true, function(err){ console.log(err) });
            done();
        });

        it.only('should read a packet', function(done){

            console.log('opening', device);
            device.open();
            console.log('open', device.interfaces[0]);

            var iface = device.interfaces[0];
                iface.claim();

            console.log('endpoints[0]', iface.endpoints[0]);

            var radioIn = iface.endpoints[0];
            var radioOut = iface.endpoints[1];

            console.log('radioOut', radioOut.direction, radioOut.transferType, radioOut.descriptor.bEndpointAddress);
            console.log('radioIn', radioIn.direction, radioIn.transferType, radioIn.descriptor.bEndpointAddress);

            radioOut.transfer([1], function(err){
                console.log('out cb', err);

                assert.equal(radioIn, iface.endpoint(0x81));

                radioIn.transfer(64, function(err, data){
                    console.log('in err / data', err, data);
                    done();
                });
            });
        });
```

and the log

```
> crazyradio-node-driver@0.0.1 test /Users/4m1r/Desktop/Crazyflie/crazyradio-node-driver
> mocha test.js



  CrazyRadio tests
    Packet tests
[timestamp] [threadID] facility level [function call] <message>
--------------------------------------------------------------------------------
[ 0.023562] [00000513] libusb: debug [libusb_get_device_list] 
[ 0.023735] [00000513] libusb: debug [libusb_get_device_descriptor] 
[ 0.023856] [00000513] libusb: debug [libusb_get_device_descriptor] 
[ 0.023924] [00000513] libusb: debug [libusb_get_device_descriptor] 
[ 0.024010] [00000513] libusb: debug [libusb_get_device_descriptor] 
[ 0.024067] [00000513] libusb: debug [libusb_get_device_descriptor] 
opening { busNumber: 20,
  deviceAddress: 26,
  deviceDescriptor: 
   { bLength: 18,
     bDescriptorType: 1,
     bcdUSB: 512,
     bDeviceClass: 0,
     bDeviceSubClass: 0,
     bDeviceProtocol: 0,
     bMaxPacketSize0: 64,
     idVendor: 6421,
     idProduct: 30583,
     bcdDevice: 39251,
     iManufacturer: 1,
     iProduct: 2,
     iSerialNumber: 29,
     bNumConfigurations: 1 },
  portNumbers: [ 1 ] }
[ 0.029535] [00000513] libusb: debug [libusb_open] open 20.26
[ 0.029695] [00000513] libusb: debug [usbi_add_pollfd] add fd 22 events 1
[ 0.029709] [00000513] libusb: debug [darwin_open] device open for access
[ 0.029744] [00003f03] libusb: debug [handle_events] poll() returned 1
[ 0.029778] [00003f03] libusb: debug [handle_events] caught a fish on the control pipe
[ 0.029796] [00003f03] libusb: debug [libusb_get_next_timeout] no URBs, no timeout!
[ 0.029802] [00003f03] libusb: debug [libusb_try_lock_events] someone else is modifying poll fds
[ 0.029805] [00003f03] libusb: debug [libusb_handle_events_timeout_completed] event handler was active but went away, retrying
[ 0.029809] [00003f03] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.029812] [00003f03] libusb: debug [handle_events] poll fds modified, reallocating
[ 0.029816] [00003f03] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
open { device: 
   { busNumber: 20,
     deviceAddress: 26,
     deviceDescriptor: 
      { bLength: 18,
        bDescriptorType: 1,
        bcdUSB: 512,
        bDeviceClass: 0,
        bDeviceSubClass: 0,
        bDeviceProtocol: 0,
        bMaxPacketSize0: 64,
        idVendor: 6421,
        idProduct: 30583,
        bcdDevice: 39251,
        iManufacturer: 1,
        iProduct: 2,
        iSerialNumber: 29,
        bNumConfigurations: 1 },
     portNumbers: [ 1 ],
     interfaces: [ [Circular] ],
     _configDescriptor: 
      { bLength: 9,
        bDescriptorType: 2,
        wTotalLength: 32,
        bNumInterfaces: 1,
        bConfigurationValue: 1,
        iConfiguration: 0,
        bmAttributes: 128,
        bMaxPower: 50,
        extra: <Buffer >,
        interfaces: [Object] } },
  id: 0,
  altSetting: 0,
  descriptor: 
   { bLength: 9,
     bDescriptorType: 4,
     bInterfaceNumber: 0,
     bAlternateSetting: 0,
     bNumEndpoints: 2,
     bInterfaceClass: 255,
     bInterfaceSubClass: 255,
     bInterfaceProtocol: 0,
     iInterface: 0,
     extra: <Buffer >,
     endpoints: [ [Object], [Object] ] },
  interfaceNumber: 0,
  endpoints: 
   [ { device: [Object],
       descriptor: [Object],
       address: 129,
       transferType: 2 },
     { device: [Object],
       descriptor: [Object],
       address: 1,
       transferType: 2 } ] }
[ 0.031801] [00000513] libusb: debug [libusb_claim_interface] interface 0
[ 0.032741] [00000513] libusb: debug [get_endpoints] building table of endpoints.
[ 0.032774] [00000513] libusb: debug [get_endpoints] interface: 0 pipe 1: dir: 1 number: 1
[ 0.032786] [00000513] libusb: debug [get_endpoints] interface: 0 pipe 2: dir: 0 number: 1
[ 0.032846] [00000513] libusb: debug [darwin_claim_interface] interface opened
endpoints[0] { device: 
   { busNumber: 20,
     deviceAddress: 26,
     deviceDescriptor: 
      { bLength: 18,
        bDescriptorType: 1,
        bcdUSB: 512,
        bDeviceClass: 0,
        bDeviceSubClass: 0,
        bDeviceProtocol: 0,
        bMaxPacketSize0: 64,
        idVendor: 6421,
        idProduct: 30583,
        bcdDevice: 39251,
        iManufacturer: 1,
        iProduct: 2,
        iSerialNumber: 29,
        bNumConfigurations: 1 },
     portNumbers: [ 1 ],
     interfaces: [ [Object] ],
     _configDescriptor: 
      { bLength: 9,
        bDescriptorType: 2,
        wTotalLength: 32,
        bNumInterfaces: 1,
        bConfigurationValue: 1,
        iConfiguration: 0,
        bmAttributes: 128,
        bMaxPower: 50,
        extra: <Buffer >,
        interfaces: [Object] } },
  descriptor: 
   { bLength: 7,
     bDescriptorType: 5,
     bEndpointAddress: 129,
     bmAttributes: 2,
     wMaxPacketSize: 64,
     bInterval: 6,
     bRefresh: 0,
     bSynchAddress: 0,
     extra: <Buffer > },
  address: 129,
  transferType: 2 }
radioOut out 2 1
radioIn in 2 129
[ 0.034498] [00000513] libusb: debug [ep_to_pipeRef] converting ep address 0x01 to pipeRef and interface
[ 0.034513] [00000513] libusb: debug [ep_to_pipeRef] pipe 2 on interface 0 matches
[ 0.034681] [0000230f] libusb: debug [darwin_async_io_callback] an async io operation has completed
[ 0.034715] [00003f03] libusb: debug [handle_events] poll() returned 1
[ 0.034725] [00003f03] libusb: debug [op_handle_events] checking fd 22 with revents = 1
[ 0.034747] [00003f03] libusb: debug [darwin_handle_callback] handling bulk completion with kernel status 0
[ 0.034756] [00003f03] libusb: debug [usbi_handle_transfer_completion] transfer 0x1039007a8 has callback 0x103b51935
[ 0.034775] [00003f03] libusb: debug [libusb_get_next_timeout] no URBs, no timeout!
[ 0.034781] [00003f03] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.034786] [00003f03] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
out cb undefined
[ 0.035264] [00000513] libusb: debug [ep_to_pipeRef] converting ep address 0x81 to pipeRef and interface
[ 0.035291] [00000513] libusb: debug [ep_to_pipeRef] pipe 1 on interface 0 matches
      1) should read a packet
[ 2.034030] [00004703] libusb: debug [libusb_release_interface] interface 0
undefined


  0 passing (2s)
  1 failing

  1) CrazyRadio tests Packet tests should read a packet:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at null.<anonymous> (/usr/local/lib/node_modules/mocha/lib/runnable.js:170:19)
      at Timer.listOnTimeout (timers.js:119:15)


```

**Comment by kevinmehall** [comment]
That looks right, so I'd guess that the device is simply not sending you a packet within the timeout. You might have to send it a control transfer to enable something, or a command that makes it reply.
