### ISSUE TITLE
fail on MacOS

### ISSUE THREAD

**Issue by yahoohung** [nonolith/node-usb#127]
I created a test app ..

```
var usb = require('usb');

var list = usb.getDeviceList();

console.log(list);
```

and I got this error message..

```
module.js:440
  return process.dlopen(module, path._makeLong(filename));
                 ^
Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/xxxx/test-usb/node_modules/usb/usb.js:5:38)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)

```

I am using OSX 10.11.4 and node v5.9.1

**Comment by kevinmehall** [comment]
You built the module for a different version of Node than the one you're using. Run `npm install --build-from-source` to recompile it.
