### ISSUE TITLE
Semver issue when installing 1.1.2

### ISSUE THREAD

**Issue by matthova** [nonolith/node-usb#135]
If I install usb by itself, with my node_modules folder empty aka
'''
npm install usb@1.1.2
'''
Usb installs fine, however the full 'npm install' from scratch fails

Here's the stack trace:

gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack TypeError: Cannot read property 'length' of undefined
gyp ERR! stack     at parse (/Users/hovanem/Sites/escher/hydraprint/node_modules/semver/semver.js:239:14)
gyp ERR! stack     at Function.valid (/Users/hovanem/Sites/escher/hydraprint/node_modules/semver/semver.js:255:11)
gyp ERR! stack     at processRelease (/Users/hovanem/Sites/escher/hydraprint/node_modules/node-gyp/lib/process-release.js:16:25)
gyp ERR! stack     at configure (/Users/hovanem/Sites/escher/hydraprint/node_modules/node-gyp/lib/configure.js:35:17)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as configure] (/Users/hovanem/Sites/escher/hydraprint/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at run (/Users/hovanem/Sites/escher/hydraprint/node_modules/node-gyp/bin/node-gyp.js:72:30)
gyp ERR! stack     at Object.<anonymous> (/Users/hovanem/Sites/escher/hydraprint/node_modules/node-gyp/bin/node-gyp.js:133:1)
gyp ERR! stack     at Module._compile (module.js:556:32)
gyp ERR! stack     at Object.Module._extensions..js (module.js:565:10)
gyp ERR! stack     at Module.load (module.js:473:32)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/hovanem/.nvm/versions/node/v6.4.0/bin/node" "/Users/hovanem/Sites/escher/hydraprint/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/hovanem/Sites/escher/hydraprint/node_modules/usb/src/binding/usb_bindings.node" "--module_name=usb_bindings" "--module_path=/Users/hovanem/Sites/escher/hydraprint/node_modules/usb/src/binding"
gyp ERR! cwd /Users/hovanem/Sites/escher/hydraprint/node_modules/usb
gyp ERR! node -v v6.4.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>

This may be a noob issue on my part. Any ideas?

**Comment by matthova** [comment]
Updated all of my node modules and the issue went away.
